server:
  port: 4444

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/

zuul:
  routes:
    api-c:
      path: /api-c/**
      serviceId: compute-service
    api-b:
        path: /api-b/**
        serviceId: compute-service